packages:
    - packages/*
    - experiments/*

allowBuilds:
    esbuild: true
    sharp: true
    workerd: true

catalog:
    '@logtape/logtape': ^2.0.2
    '@types/node': ^25.2.0
    drizzle-orm: ^0.45.1
    postgres: ^3.4.8
    prettier: ^3.8.0
    publint: ^0.3.17
    typescript: ^5.9.3
    valibot: ^1.2.0
    wrangler: ^4.62.0
    better-result: ^2.7.0
    tsx: ^4.21.0
    ofetch: ^1.5.1

ignoreDepScripts: true

patchedDependencies:
    hosted-git-info: patches/hosted-git-info.patch
    validate-npm-package-name: patches/validate-npm-package-name.patch
