packages:
    - packages/*
    - experiments/*

catalog:
    '@logtape/logtape': ^2.0.5
    '@types/node': ^25.5.0
    drizzle-orm: ^0.45.2
    postgres: ^3.4.8
    prettier: ^3.8.0
    publint: ^0.3.18
    typescript: ^6.0.2
    valibot: ^1.3.1
    wrangler: ^4.79.0
    better-result: ^2.7.0
    tsx: ^4.21.0
    ofetch: ^1.5.1

ignoreDepScripts: true

onlyBuiltDependencies:
    - esbuild
    - workerd
    - sharp

patchedDependencies:
    hosted-git-info: patches/hosted-git-info.patch
    validate-npm-package-name: patches/validate-npm-package-name.patch
