name: Build & Test

on:
    push:
        branches: [main]
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [24.x]
            fail-fast: false
        steps:
            - name: Checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
            - name: Use Node v${{ matrix.node-version }}
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use pnpm
              uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
            - name: Install Dependencies
              run: pnpm install
            - name: Lint
              run: npm run lint
            - name: Check
              run: npm run check
            - name: Test
              run: npm run test
